# Generated by Django 5.2.7 on 2026-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cinemas/')),
                ('description', models.TextField()),
                ('program_phone', models.CharField(max_length=50)),
                ('reservations_phone', models.CharField(max_length=100)),
                ('admin_phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('opening_hours', models.CharField(default='Daily, 10:00 - 23:00', max_length=100)),
                ('halls_count', models.IntegerField(default=3)),
                ('google_maps_embed', models.TextField(help_text='Google Maps iframe code')),
            ],
        ),
    ]
