# Generated by Django 5.2.7 on 2026-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_news_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin Task',
                'verbose_name_plural': 'Admin Tasks',
                'ordering': ['-priority', 'deadline'],
            },
        ),
    ]
