# Generated by Django 5.2.7 on 2026-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_admin_task_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintask',
            options={'ordering': ['deadline', '-priority'], 'verbose_name': 'Admin Task', 'verbose_name_plural': 'Admin Tasks'},
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='halls_count',
        ),
        migrations.AlterField(
            model_name='admintask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
