# Generated by Django 5.2.7 on 2026-01-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_shop_category_shop_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop_Category',
            new_name='ShopCategory',
        ),
        migrations.RenameModel(
            old_name='Shop_Products',
            new_name='ShopProducts',
        ),
    ]
