# Generated by Django 5.2.7 on 2026-01-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_shop_category_shopcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='product_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
