# Generated by Django 5.2.7 on 2025-10-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_rows', models.PositiveIntegerField()),
                ('total_columns', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('is_3d', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP')], default='regular', max_length=11)),
                ('is_functional', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='hall.hall')),
            ],
            options={
                'unique_together': {('hall', 'row', 'column')},
            },
        ),
    ]
