# Generated by Django 5.2.7 on 2026-01-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_admintask_options_remove_cinema_halls_count_and_more'),
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.cinema'),
        ),
    ]
