# Generated by Django 5.2.7 on 2026-01-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_remove_hall_is_vip_alter_hall_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_type',
        ),
    ]
