# Generated by Django 5.2.7 on 2025-11-06 11:56

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
